CHOOSING_ACTION, AWAITING_PACK_NAME, AWAITING_PRIVACY, PROCESSING_STICKERS, AWAITING_EMOJI, EDITING_PHOTOS, EDITING_STICKERS = range(7)
ADMIN_PANEL, ADMIN_USER_LIST, ADMIN_PACK_LIST, ADMIN_PACK_ACTION = range(7, 11)
ADMIN_ALL_PACKS, ADMIN_ALL_PACK_ACTION, VIDEO_VALIDATION, PROCESSING_MEDIA = range(11, 15)
AWAITING_IMAGE_SELECTION = 15  # Новое состояние для выбора обработанных изображений
